// Paste your CSV data here as a string
const csvData = `German,English
Touristen,"tourists"
Schloss,"castle/palace/lock"
Brandenburger Tor,"Brandenburg Gate"
Neuschwanstein,"Neuschwanstein Castle"
besichtigen,"are touring/saw/tour"
Wörterbuch,"dictionary/wordbook"
Brille,"glasses/spectacles/eyeglasses"
Laptop,"laptop"
zweihundert,"two hundred"
Kamera,"camera"
grau,"gray/grey"
Koffer,"suitcase/bag"
lila,"purple/lilac"
Problem,"problem"
Rucksack,"backpack/rucksack/knapsack"
verboten,"prohibited/forbidden/not allowed"
zum Schalter,"to counter"
richtig,"correct/right/accurate"
Kugelschreiber,"pen/biro/ballpoint pen"
Formular,"form/questionnaire"
unterschreiben,"sign"
Moment,"moment"
Zoll,"customs/customs office"
Wochen,"weeks"
Flugnummer,"flight number"
Visum,"visa"
Jahr,"year"
vielleicht,"maybe/perhaps"
Februar,"February"
nächsten,"next/closest"
August,"August"
Verwandten,"relatives"
Getränke,"drinks"
Geschäfte,"stores/businesses/business"
geschlossen,"closed/locked/shut"
Familie,"family"
Hausaufgaben,"homework/homework assignments"
Feiertag,"holiday/bank holiday/public holiday"
Stunden,"lessons/hours/classes"
müsst,"have to/need to/have got to"
Stunde,"hour"
kurz,"short/brief"
langweilig,"boring/dull/tedious"
diesen,"this/that/these"
Ausweis,"ID card/ID/identification card"
Erwachsene,"adult/adults"
welchen,"which/what"
finden,"find"
Horrorfilm,"horror movie/horror film"
Wochenende,"weekend"
vierzig,"forty"
Freitag,"Friday"
wohin,"where to/where"
schließt,"is connecting/shuts/shut"
Biergarten,"beer garden"
jedes,"all/every/anything"
hungrig,"hungry"
Kekse,"cookies/biscuits"
Liter,"liters/liter/liters of"
Flaschen,"bottles/bottles of"
grün,"green"
Gras,"grass"
frisch,"fresh"
Schokolade,"chocolate"
Spinat,"spinach"
Gemüse,"vegetables/vegetable"
weniger,"less/fewer"
langsam,"slowly"
bekommt,"is getting/getting/get"
alles,"everything/all"
Sauerkraut,"sauerkraut"
Currywurst,"curry sausage/currywurst/curried sausage"
Knödel,"dumplings"
Mayo,"mayo/mayonnaise"
Brezel,"pretzel"
scharf,"spicy/sharp/hot"
Senf,"mustard"
Eier,"eggs"
Nussallergie,"nut allergy"
ihn,"him"
backen,"bakes/baked/making"
Kartoffelsalat,"potato salad"
nichts,"nothing"
am besten,"the best/best"
Dezember,"December"
Obst,"fruit"
Eiskaffee,"ice cream coffee/coffee with ice cream/iced coffeee"
Lieblingsessen,"favorite food/favourite food"
Dorf,"village/town/small town"
Großmutter,"grandmother/grandma/nan"
Großvater,"grandfather/granddad/grandad"
Großeltern,"grandparents"
Haustiere,"pets"
Computer,"computers/computer"
Juni,"June"
arbeitslos,"unemployed/jobless/out of work"
Auge,"eye"
Japan,"Japan"
Auto,"car/auto/automobile"
Motorrad,"motorcycle/motorbike/bike"
reisen,"traveling/travel/are going"
brav,"well-behaved/good"
Januar,"January"
Kinder,"children/kids/kids'"
Praktikum,"internship/traineeship/practicum"
Job,"job"
Schildkröte,"turtle/tortoise"
Geschwister,"siblings"
ihren,"their/to their/for their"
reich,"rich/wealthy/affluent"
Freizeit,"free time/leisure time/spare time"
Beamter,"civil servant/public official/official"
seinen,"with their/her/their"
Haus,"house/home"
zufrieden,"content/satisfied/pleased"
Beamtin,"civil servant/public official/official"
kaputt,"broken/broken down/busted"
Fenster,"window"
Internet,"internet"
Tür,"door/doorway"
Dusche,"shower"
funktioniert,"work/works/is working"
Frühstück,"breakfast"
Sessel,"armchair/reclining chair/easy chair"
Rezeption,"reception desk/reception"
Fernseher,"TV/TV set/television"
ruhig,"quiet/peaceful/still"
Fitnessstudio,"gym/health club/exercise centre"
Balkon,"balcony"
Buchladen,"bookstore/bookshop"
gibt es,"is/there are/is there"
Flughafen,"airport"
Strand,"beach/shore"
Bar,"bar"
Ausflug,"excursion"
Schlüssel,"key"
Zimmer,"room"
willkommen,"welcome"
Ihren,"It/your/yours"
Pass,"passport"
nehme,"will have/participate/take"
Einzelzimmer,"single room"
Nacht,"night"
Doppelzimmer,"double room"
hundert,"one hundred"
Nächte,"nights"
rot,"red"
Bild,"painting/picture/photo"
Kopfkissen,"pillow"
weich,"soft/squishy"
Pflanzen,"plants"
Bettdecke,"bedspread/blanket/bed blanket"
Esszimmer,"dining room"
Stühle,"chairs"
Küche,"kitchen"
schmutzig,"dirty/filthy/grimy"
Kühlschrank,"refrigerator/fridge/fridge freezer"
Mikrowelle,"microwave/microwave oven"
Bücher,"books"
Kaffeetisch,"coffee table"
Regal,"shelf/rack/shelving"
Wohnzimmer,"living room/lounge/sitting room"
Sofa,"sofa"
Blumen,"flowers"
Vase,"vase"
Nachbar,"neighbor/neighbour"
Nachbarin,"neighbor/neighbour"
unser,"our"
weiß,"white"
leise,"quiet/silent"
unsere,"our/ours"
schwarz,"black"
Treppe,"stairs/steps/staircase"
Mehrfamilienhaus,"apartment building/multi-family residence/residential building"
Garten,"garden/yard"
zurzeit,"currently/at the moment"
allein,"alone"
wohnen,"live/lived/are living"
sonntags,"on Sundays"
Reis,"rice"
Hähnchen,"chicken"
Nudeln,"noodles/pasta"
freitags,"on Fridays"
Freundinnen,"friends/girlfriends"
zum Abendessen,"to dinner/for dinner"
Büro,"office"
Kollegen,"colleague/coworkers'/coworker"
Schinken,"ham"
Tasse,"cup/mug"
Brötchen,"roll/bread roll/bun"
zum Mittagessen,"for lunch"
treffe,"am meeting/meeting/meet"
jede,"any/all/each"
triffst,"join/meet/hit"
trifft,"is meeting/join/meeting"
Donnerstag,"Thursday"
Banane,"banana"
morgens,"in the mornings/in the morning"
Joghurt,"yogurt/yoghurt"
Müsli,"muesli/cereal/granola"
zum Frühstück,"for breakfast"
isst,"eats/is eating/eating"
pro,"per"
Yoga,"yoga"
abends,"in the evenings/in the evening"
einmal,"once"
Sport,"sports/exercise/sport"
wie oft,"how often"
früh,"early"
noch,"still"
gute Nacht,"good night"
Viertel,"quarter"
bis morgen,"see you tomorrow"
vor,"to/in front of/of"
Leute,"people"
Pommes,"fries/french fries/chips"
Handy,"cell phone/mobile phone/mobile"
Musik,"music"
Band,"band"
schmecken,"taste"
hören,"hear/listen to/listen"
uns,"us"
dich,"you/yourself"
Wiesn-Herz,"heart cookie"
Riesenrad,"Ferris wheel"
Weißbier,"wheat beer"
sehe,"am watching/see/watch"
neunzehnten,"nineteenth"
September,"September"
achtzehnten,"eighteenth"
Oktober,"October"
beginnt,"begin/is starting/start"
endet,"finishes/ends/finish"
Oktoberfest,"Oktoberfest"
beliebt,"popular/well-liked"
Spaß,"fun"
zum Oktoberfest,"to Oktoberfest"
wollen,"want/want to/won't"
lieben,"loves/love/loved"
Kanadierin,"Canadian"
Studenten,"students/student"
freundlich,"friendly"
Kanadier,"Canadians/Canadian"
lebt,"live/is living/are living"
seid,"did/have/be"
seine,"your/her/his"
Eltern,"parents"
ihre,"her/hers/theirs"
Deutsche,"German/a German/Germans"
Amerikanerin,"American"
Deutscher,"German"
arbeitest,"work/are working/working"
Amerikaner,"American"
Zürich,"Zurich"
arbeitet,"work/works/are working"
fast,"almost/nearly"
lustig,"funny"
intelligent,"intelligent"
Kind,"child/kid"
Baby,"baby"
Monate,"months"
Mädchen,"girl"
Geschichte,"history"
achtzehn,"eighteen"
Psychologie,"psychology"
Jahre,"years/years'"
neunzehn,"nineteen"
studieren,"study/are studying/have studied"
glücklich,"happy"
gute Besserung,"feel better/get well"
hurra,"hooray/woohoo/yippie"
gesund,"healthy/fit/well"
mehr,"more/anymore/left"
Zahnschmerzen,"toothache"
im Bett,"in bed"
schlafen,"sleep"
Fieber,"fever"
Bauchschmerzen,"stomachache/tummyache"
müssen,"have got to/have to/need to"
bleiben,"stay/being/stopped"
Name,"name"
siebzehn,"seventeen"
wie viel Uhr,"what time"
machen,"go on/makes/offered"
sechzehn,"sixteen"
Termin,"appointment/date/deadline"
Tablette,"pill/tablet"
geh,"go/leave"
iss,"eat"
Kopfschmerzen,"headache/headaches"
Krankenhaus,"hospital"
trink,"drink"
schlafe,"sleep/am asleep/am sleeping"
viel,"much"
müde,"tired/sleepy/weary"
traurig,"sad/unhappy"
nachts,"at night/at nighttime"
Durst,"thirst/thirsty"
krank,"sick"
arbeiten,"work"
Lust,"desire/in the mood"
leider,"unfortunately/sadly/regrettably"
Mittwoch,"Wednesday"
schon,"already/yet"
Pläne,"plans"
lernen,"learn/studies/study"
grillen,"grill"
wollt,"want/wish/will"
Woche,"week"
Wald,"forest/wood/woods"
Hexe,"witch"
campe,"am camping/go camping/camp"
Podcasts,"podcasts"
will,"wants/wants to/want"
hört,"hears/hear/listens to"
Jazz,"jazz"
Videospiele,"video games"
willst,"want/want to"
höre,"listening/to listen to/hear"
Geige,"violin/fiddle"
Film,"movie/film"
Tennis,"tennis"
Instrument,"instrument"
tanzt,"is dancing/are dancing/dances"
Gitarre,"guitar"
tanzen,"dance"
Hobbys,"hobbies"
surfen,"surf/surfing"
tanze,"dance/am dancing"
zu Hause,"at home/home"
könnt,"can/are able to/know"
Geschenk,"gift/present"
feiert,"celebrate/celebrates/is celebrating"
feiern,"celebrate/are celebrating/celebrating"
macht,"is/comes to/is making"
möchtet,"want/would like to/like"
Einladung,"invitation"
ihr,"she/her/to her"
auf jeden Fall,"definitely"
Picknick,"picnic"
kann,"am able to/know/can"
Juli,"July"
kannst,"can/are able to/could"
siebten,"seventh"
zehnten,"tenth"
vierten,"fourth/4th"
dritten,"third"
zweiten,"second/2nd"
Party,"party"
Mai,"May"
mache,"am turning/am making/work"
Geburtstag,"birthday"
morgen,"tomorrow"
ersten,"first"
März,"March"
April,"April"
Taxi,"taxi"
Straße,"street/road"
wiederholen,"repeat"
Adresse,"address"
bis zum Hotel,"to the hotel"
alles Gute,"take care/all the best/take"
wie lange,"how long"
dauert,"lasts/takes/does last"
vierzehn,"fourteen/14"
zu Fuß,"by foot/on foot"
Taxifahrt,"taxi ride/cab ride"
warten,"hold on/have been/wait"
dreizehn,"thirteen/13"
Bushaltestelle,"bus stop"
elf,"eleven/11"
Nummer,"number"
zwölf,"twelve"
fahren,"are riding/are departing/run"
Bus,"bus"
fünfzehn,"fifteen/15"
circa,"approximately"
dann,"then"
geradeaus,"straight ahead"
besuchen,"visit"
Stadtmuseum,"city museum"
Fluss,"river"
Stadtzentrum,"city center"
sehen,"see"
Zoo,"zoo"
Kunstmuseum,"art museum"
bar,"cash/in cash"
zusammen,"together"
fünfunddreißig,"thirty-five/35"
fünfundzwanzig,"twenty-five/25"
getrennt,"separately"
Obstsalat,"fruit salad"
süß,"sweet/cute"
Zucker,"sugar"
ohne,"without"
Eis,"ice cream/ice"
Apfelkuchen,"apple cake/apple pie"
Nachtisch,"dessert/sweet"
guten Appetit,"enjoy your meal"
Fleisch,"meat"
bestellen,"order"
esse,"am eating/am having/have"
Suppe,"soup"
trinke,"drink/am drinking"
möchten,"would like to/would like"
mich,"myself/me/I"
Glas,"glass/jar"
Rotwein,"red wine"
trinken,"drink"
Apfelschorle,"sparkling apple juice/carbonated apple juice/apple juice spritzer"
lieber,"kind/prefers/prefer"
griechisch,"Greek"
später,"later/later on"
essen,"eat"
Hunger,"hunger/hungry"
italienisch,"Italian"
keinen Hunger,"not hungry"
frei,"free/available"
Zugtür,"train door"
Speisewagen,"dining car/diner car"
Sitz,"seat/place/chair"
Station,"station"
nächste,"next/closest"
hinten,"in the back/at the back/in the rear"
fällt,"fall/is falling/cases"
können,"are able to/knew/can"
Kreditkarte,"credit card"
Reisezentrum,"travel center/travel centre"
stornieren,"cancel"
zahlen,"pay/to pay/are paying"
Gleis,"track/platform"
ICE,"intercity express/ICE"
auf,"on to/on top of/onto"
Verspätung,"delay"
Achtung,"careful/attention/watch out"
es gibt,"there are/there is/there's"
Abfahrt,"departure"
spät,"late"
halb,"half"
Minuten,"minutes"
Uhr,"watch/clock/o'clock"
Zug,"train"
genau,"exactly/precisely"
nach,"for/about/to"
dreißig,"thirty/30"
kosten,"is/try/were"
Hin- und Rückfahrt,"round-trip ticket/round trip/return ticket"
Fahrkarte,"ticket"
zwanzig,"twenty/20"
Fahrkarten,"tickets"
Toiletten,"toilets/bathrooms/restrooms"
Schuhe,"shoes"
Aufzug,"elevator/lift"
Pullover,"sweater/jumper"
schick,"stylish/fashionable/chic"
Jeans,"jeans/pair of jeans"
passt,"fit/is suitable/fits"
L,"large"
S,"small"
Größe,"size"
T-shirt,"T-shirt"
Hemd,"shirt"
Kleid,"dress"
Sakko,"suit jacket/jacket/sport coat"
suche,"am looking for/look for/seek"
musst,"have got to/have to/need to"
muss,"needs to/has to/has got to"
aufgeregt,"excited/eager/jumpy"
Bluse,"blouse/shirt/top"
kaufen,"buy/to get/to purchase"
gehe,"am going/walking/go"
Jobinterview,"job interview/interview"
nervös,"nervous/on edge/flustered"
Kaufhaus,"department store/store"
für,"for"
Dienstag,"Tuesday"
Montag,"Monday"
fantastisch,"fantastic/great/terrific"
Bett,"bed"
Badezimmer,"bathroom/restroom/washroom"
Bücherregal,"bookcase/bookshelf"
dunkel,"dark"
hell,"bright/light"
Lampe,"lamp/light"
sauber,"clean/tidy/neat"
Wohnung,"apartment/flat"
wer,"who"
Schreibtisch,"desk"
Couch,"couch"
Schlafzimmer,"bedroom"
magst,"like"
Schrank,"closet/cabinet/cupboard"
bequem,"comfortable/comfortably"
brauchen,"need/do need"
wir,"we"
Teppich,"carpet/rug"
den,"her/the/that"
mag,"like/likes/disliked"
brauchst,"need/use"
hässlich,"ugly/hideous/unsightly"
haben,"have/do have/have had"
Stuhl,"chair"
Tisch,"table/desk"
modern,"modern"
bis,"until/till/'til"
geöffnet,"open"
Eintrittskarte,"admission ticket/[admission/entry/entrance] [ticket/pass/card]"
wann,"when/what time/at what time"
heute Nachmittag,"this afternoon"
um,"for/to/of"
schade,"harm/too bad"
Spiel,"game/match/play"
Konzert,"concert/concerto/show"
am,"by the/the/a"
heute Abend,"this evening/tonight"
Sonntag,"Sunday"
Samstag,"Saturday"
Zeit,"time"
schwimmen,"swim/to float"
ins,"this/to the/that"
Geld,"money"
Schwimmbad,"swimming pool"
gehen,"go/walk/leave"
möchte,"would like to/would like"
möchtest,"would like to/like/would like"
am Wochenende,"on the weekend"
Freunde,"friends/friends'"
joggen,"to jog/jogging"
spielen,"playing/are playing/will play"
singst,"sing/are singing"
gern,"like/liked to/happy to"
singt,"sings/sing/is singing"
singe,"sing/am singing"
fotografiere,"take photos/take pictures"
surft,"goes surfing/is surfing/surfs"
jogge,"am jogging/jog/jogging"
Basketball,"basketball"
frühstückt,"are eating breakfast/eats breakfast/is eating breakfast"
Morgen,"morning"
Fußball,"soccer/football"
Volleyball,"volleyball"
Urlaub,"vacation/a vacation/holidays"
joggt,"jogs/is jogging"
jeden,"any/all/each"
Tag,"day"
surfe,"surf/go surfing"
surfst,"surf/go surfing"
frühstücke,"eat breakfast/am eating breakfast"
joggst,"jog/are jogging"
so,"that/as/so"
heute Morgen,"this morning"
machst,"work/are doing/are taking"
frühstückst,"are eating breakfast/eat breakfast"
warum,"why"
spricht,"speaks/does speak/speak"
lernt,"learns/is studying/learn"
Muttersprache,"mother tongue/native language/first language"
viele,"many/a lot of/lots of"
Russisch,"Russian"
lernst,"learn/study/are studying"
lerne,"learn/am meeting/study"
Spanisch,"Spanish"
schnell,"quickly/rapidly"
sprichst,"are speaking/speak/talk"
nur,"only/just/merely"
welche,"which"
Sprachen,"languages"
Schwedisch,"Swedish"
schwer,"difficult/hard/tough"
Ihr,"she/your/her"
Französisch,"French"
nicht,"not"
sein,"your/to be/be"
einfach,"easy/simple"
toll,"great/awesome/terrific"
Türkisch,"Turkish"
Polnisch,"Polish"
dünn,"thin/slim/smallest"
perfekt,"perfect"
kommt,"is/is coming/comes"
Schnecke,"snail/slug"
heißt,"is/name is/is called"
liebe,"love"
liebst,"love"
Fisch,"fish"
Mitbewohnerin,"roommate/roommate's"
Partnerin,"partner"
keinen,"any/not any/no"
Partner,"partner/partners/partner's"
Mitbewohner,"roommate/roomie/flatmate"
keine,"any/n't/no"
Oma,"grandma/grandmother/nan"
Tante,"aunt/auntie/aunty"
liebt,"loves/love"
Opa,"grandpa/grandfather/granddad"
deinen,"your/to your/for your"
meinen,"mean/mine/to my"
hat,"has/was/is"
hast,"have/are/were"
habe,"am/have been/did"
einen,"an/a/one"
Freund,"boyfriend/partner"
Onkel,"uncle"
warm,"warm"
Sommer,"summer"
wandert,"hike/hikes/hiking"
Sonnencreme,"sunscreen/suntan lotion/sun cream"
wandere,"am hiking/go hiking/hike"
wandern,"traveling/hiking/hike"
wanderst,"hiking/hike/go hiking"
neblig,"foggy/misty"
Frühling,"spring/springtime"
Wasserflasche,"water bottle"
stark,"strong/hard/harder"
Schal,"scarf/shawl"
jetzt,"now/at the moment/currently"
Winter,"winters/winter"
schneit,"is snowing/snows"
Herbst,"fall/autumn"
habt,"did/have/meet"
windig,"windy"
im,"this/to the/in the"
Regenschirm,"umbrella"
schlecht,"bad/ill/poor"
regnet,"rains/is raining"
es,"it"
sonnig,"sunny"
heute,"today"
Wetter,"weather"
bewölkt,"cloudy"
Erdbeeren,"strawberries"
gern geschehen,"you are welcome"
Kartoffeln,"potatoes"
vielen Dank,"thank you very much"
zehn,"ten"
Döner,"doner kebab/kebab"
Tomaten,"tomatoes"
neun,"nine"
Kilo,"kilos of/kilo of/kilos"
wirklich,"really/actually/truly"
fünf,"five"
sieben,"seven"
sechs,"six"
Euro,"euros/euro"
von,"from/'s/on"
null,"zero"
Dollar,"dollar/dollars"
kostet,"is/does cost/costs"
Orangen,"oranges"
Marktplatz,"marketplace/market"
drei,"three"
eins,"one"
zwei,"two"
Anwalt,"lawyer/barrister/solicitor"
Russland,"Russia"
Anwältin,"lawyer/a lawyer"
Schweden,"Sweden"
Künstler,"an artist/artists'/performer"
lebst,"live/living"
lebe,"live/am living"
leben,"lived/living/are living"
Polizist,"police officer/policeman/a police officer"
Schüler,"students/pupil/student"
Deutsch,"German"
spreche,"am talking/speak/pronounce"
sprechen,"speak/are speaking"
Englisch,"English"
kein,"any/no/not an"
freut mich,"nice to meet you/nice"
wie,"as/such/like"
heiße,"hot/am called"
heißen,"hot/name/go"
kommen,"arrives/comes on/do come"
sind,"feel/have/are"
Herr,"Mr./gentleman"
Sie,"They/It/your"
Kanzlerin,"chancellor/the chancellor/a chancellor"
U-Bahnstation,"subway station"
Geldautomat,"ATM/cash dispenser/cashpoint"
neu,"new"
weit weg,"far away/far"
je,"for each/per/once"
Universität,"university/uni/college"
Kino,"movie theater/cinema/movie theatre"
rechts,"on the right/right/the right"
links,"on the left/left/to the left"
Bäckerei,"bakery/baker's"
Supermarkt,"supermarket/grocery store"
ha,"ha"
Museum,"museum"
Hotel,"hotel"
billig,"cheap/inexpensive"
elegant,"elegant"
Café,"coffee shop/cafe/coffeehouse"
alt,"old"
in der Nähe,"close/nearby/near"
Kirche,"church/kirk"
Apotheke,"pharmacy/drugstore/chemist"
Bibliothek,"library"
Bahnhof,"train station/railway station/rail station"
Markt,"market/marketplace"
da drüben,"over there"
Park,"park"
Taxistand,"taxi stand"
Klavier,"piano"
spiele,"am playing/play/playing"
spielst,"are playing/playing/play"
Schach,"chess"
spielt,"is/are playing/is playing"
oft,"often"
schwimmt,"swim/is swimming/are floating"
malt,"is drawing/paints/draws"
kocht,"make/cooks/is cooking"
immer,"always"
schwimmst,"swim/are floating/float"
kochst,"are boiling/make/boil"
malst,"are painting/paint"
eh,"in any case/hey/anyway"
male,"paint/am painting/draw"
nie,"never"
schwimme,"swim/am swimming/swimming"
manchmal,"sometimes/at times"
koche,"am making/make/will cook"
acht,"eight"
Lehrerin,"teacher/a teacher"
Arbeit,"work/piece of work/job"
Lehrer,"teacher/instructor/schoolteacher"
interessant,"interesting"
aber,"but/however"
stressig,"stressful"
Arzt,"doctor/physician"
Studentin,"a student/college student/student"
Ärztin,"doctor/a doctor"
Student,"college student/university student/student"
Freundin,"girlfriend/friend/friend's"
deine,"your/yours"
Beruf,"profession/job/occupation"
dein,"your"
was,"what"
Professorin,"professor/a professor"
Professor,"professor/a professor"
au,"ow/oh/ouch"
Kellnerin,"waitress/server"
sie,"she"
Schauspieler,"actor"
Schauspielerin,"actress/actor"
laut,"loud/noisy/loudly"
aufregend,"exciting/thrilling"
teuer,"expensive/costly/dear"
cool,"cool"
auch,"also/as well/too"
Frankreich,"France"
aus,"made of/out/off"
komme,"come/will come/am coming"
München,"Munich"
Stadt,"city/town"
Wien,"Vienna"
Österreich,"Austria"
woher,"where/from/where from"
kommst,"come/are coming/are"
Amerika,"America"
in,"in/with/inside"
Deutschland,"Germany"
klein,"small"
Kanada,"Canada"
wunderbar,"wonderful/splendid/excellent"
Schnitzel,"schnitzel/schnitzels"
zu,"with/for/too"
Rechnung,"check"
Essen,"food"
Wurst,"sausage"
Restaurant,"restaurant"
Salz,"salt"
Entschuldigung,"sorry/excuse me/apologies"
Kellner,"waiter"
Speisekarte,"menu"
kalt,"cold"
Mineralwasser,"mineral water"
das,"that/this/so"
Ei,"egg"
Sandwich,"sandwich"
hier,"here"
heiß,"hot"
lecker,"delicious"
Pizza,"pizza"
mit,"with"
Salat,"salad"
Käse,"cheese"
bis später,"see you later"
es tut mir leid,"I am sorry"
natürlich,"of course"
ehe,"anyways/in any case/marriage"
bis bald,"see you soon"
prost,"cheers"
OK,"OK"
auf Wiedersehen,"goodbye"
er,"it's/he's/him"
es geht,"I'm all right"
sah,"saw/looked/watched"
gut,"good"
guten Tag,"hello"
wie geht's,"how are you?"
super,"super/great/fantastic"
Bär,"bear"
Eule,"owl"
oh,"oh/aw"
wo,"where"
Maus,"mouse"
Katze,"cat"
Elefant,"elephant"
schön,"beautiful"
jung,"young"
Hund,"dog"
Junge,"boy"
der,"this/to the/of the"
ie,"ie"
die,"this/the/that"
lag,"lied/was lying/lay"
nett,"nice"
klug,"smart"
groß,"tall"
sehr,"very"
ist,"is/there is/'s"
Tochter,"daughter"
Sohn,"son"
du,"you"
bist,"are/have been/were"
Frau,"woman/wife/Ms."
ach,"oh"
Mann,"husband/man/guy"
Bruder,"brother"
mein,"my"
meine,"mine/think/my"
Schwester,"sister"
Mutter,"mother"
bin,"am/will be/feel"
eine,"an/a/one"
ein,"a/one/submit"
vier,"four"
ich,"I"
Vater,"father"
ja,"yes"
Bier,"beer"
oder,"or"
tschüss,"bye"
nein,"no"
danke,"thank you"
Wasser,"water"
Brot,"bread"
Wein,"wine"
Tee,"tea"
hallo,"hello"
Kaffee,"coffee"
bitte,"please"
Milch,"milk"
a,"A/≅ M"
und,"and"`;


let words = [];
let currentIndex = 0;

function shuffleArray(array) {
for (let i = array.length - 1; i > 0; i--) {
const j = Math.floor(Math.random() * (i + 1));
[array[i], array[j]] = [array[j], array[i]];
}
return array;
}

document.addEventListener('DOMContentLoaded', () => {
words = shuffleArray(parseCSV(csvData));
if (words.length > 0) {
showWord();
} else {
console.error('No words parsed from CSV');
document.getElementById('deutsch-word').textContent = 'Error: No words loaded';
}
});

function parseCSV(csv) {
const lines = csv.split('\n');
return lines.slice(1).map(line => {
const [deutsch, english] = line.split(',');
return { deutsch: deutsch.trim(), english: english.replace(/"/g, '').split(',')[0].trim() };
}).filter(word => word.deutsch && word.english);
}

function showWord() {
if (words.length > 0) {
document.getElementById('deutsch-word').textContent = words[currentIndex].deutsch;
document.getElementById('english-meaning').style.display = 'none';
}
}

document.getElementById('show-meaning').addEventListener('click', () => {
if (words.length > 0) {
document.getElementById('english-meaning').textContent = words[currentIndex].english;
document.getElementById('english-meaning').style.display = 'block';
}
});

document.getElementById('prev').addEventListener('click', () => {
if (words.length > 0) {
currentIndex = (currentIndex - 1 + words.length) % words.length;
showWord();
}
});

document.getElementById('next').addEventListener('click', () => {
if (words.length > 0) {
currentIndex = (currentIndex + 1) % words.length;
showWord();
}
});
